### ISSUE TITLE
Adding purge whitelist options breaks Production Build

### ISSUE THREAD

**Issue by fayazara** [nuxt-community/tailwindcss-module#122]
### Version
@nuxtjs/tailwindcss:  1.4.1
nuxt:  2.11.0

### Reproduction Link
None as Build fails, bug is in dev env.

### Steps to reproduce
Add purge options as mentioned in the docs - https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css

Example: 
```
module.exports = {
  purge: {
    options: {
      whitelistPatterns: [/agile*/],
      whitelistPatternsChildren: [/agile*/]
    }
  },
  variants: {},
  plugins: []
}
```

### What is Expected?
Skip the agile classes and add them in the css output in production build

### What is actually happening?
Breaks the production build with the below error.

```
ERROR in ./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css& (./node_modules/css-loader/dist/cjs.js??ref--3-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/string-replace-loader??ref--12!./.nuxt/components/nuxt-loading.vue?vue&type=style&index=0&lang=css&)
8:10:13 PM: Module build failed (from ./node_modules/postcss-loader/src/index.js):
8:10:13 PM: TypeError: Cannot read property 'filter' of undefined
8:10:13 PM:     at /opt/build/repo/node_modules/tailwindcss/node_modules/@fullhuman/postcss-purgecss/lib/postcss-purgecss.js:1:483
8:10:13 PM:     at LazyResult.run (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:295:14)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:208:26)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:14)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:14)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:14)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:14)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:14)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:14)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:14)
8:10:13 PM:     at /opt/build/repo/node_modules/postcss/lib/lazy-result.js:250:14
8:10:13 PM:     at new Promise (<anonymous>)
8:10:13 PM:     at LazyResult.async (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:246:23)
8:10:13 PM:     at LazyResult.then (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:127:17)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:212:17)
8:10:13 PM:     at LazyResult.asyncTick (/opt/build/repo/node_modules/postcss/lib/lazy-result.js:221:1
```

**Comment by mornir** [comment]
My guess is that you're missing the content property. Cannot read property 'filter' of undefined, `undefined` being the `content` property.
Adding `content: []` should fix the problem, but then you wouldn't be purging anything. Could you try adding the following default config and see if it's working?
```js
module.exports = {
  purge: {
   enabled: process.env.NODE_ENV === 'production',
    content: [
      'components/**/*.vue',
      'layouts/**/*.vue',
      'pages/**/*.vue',
      'plugins/**/*.js',
      'nuxt.config.js',
    ],
    options: {
      whitelistPatterns: [/agile*/],
      whitelistPatternsChildren: [/agile*/]
    }
  },
  variants: {},
  plugins: []
}

**Comment by fayazara** [comment]
Well, the build is succeding now, but the whilelisting is now working. 

I am still not getting classes for my vue-agile third party plugin and everything is still messed up.

**Comment by mornir** [comment]
a wild guess: try
`whitelistPatterns: [/agile.*/]`
(with a dot)

(and I don't think that you need whitelistPatternsChildren)

**Comment by fayazara** [comment]
Tried, does not work.

Even the other nuxt-modules classes are now being removed. For Eg, nuxt-lazy load has stopped working since its classes are now being purged.

**Comment by fayazara** [comment]
Damn this update is so worse than I had thought

**Comment by fayazara** [comment]
Should I just downgrade to nuxt where it had the OG purgeCSS built in and prev TailwindCSS version.

**Comment by mornir** [comment]
ah sorry I meant `whitelistPatterns: [/^agile.+*/]`. Make sure that your regex is correct (https://regex101.com/)
yeah, you also need whitelist nuxt lazy load classes.

**Comment by fayazara** [comment]
Nope, does not work. I tried manually adding every single agile class in the whitelist array, it still didnt work.

I know its not vue-agile's issue because it works in dev server. 

How it looks in dev server
![image](https://user-images.githubusercontent.com/15716057/84810555-23dc2880-b029-11ea-932c-970a31c9d513.png)


Here is how it looks in production build
![image](https://user-images.githubusercontent.com/15716057/84810415-f2635d00-b028-11ea-8c1d-cfd41cd8bdaf.png)


I even tried
```
purge: {
  enabled: false
}
```

The slider still wont work, this is very frustating, I used to work with tailwindcss and nuxt every single time in my work flow and never came across this issue.

**Comment by jhull** [comment]
Same issue here. Whitelisting not working at all...

**Comment by bart** [comment]
Same issue here. Using `purgecss-whitelister` module and getting many errors of

```
Module build failed (from ./node_modules/postcss-loader/src/index.js):
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (7:0)
```

The only option I currently see to fix this quickly is disabling purging in tailwind and using nuxt-purgecss plugin for purging

**Comment by Atinux** [comment]
Please upgrade to Nuxt Tailwind v2 or v3 since we don't maintain anymore the v1 since Tailwind has an official way of purging the css now.

**Comment by kolaente** [comment]
I'm hitting this as well with the tailwind cli. My purge options look like this:

```js
    purge: {
        content: [
            '../../../../../../../vendor/hyva-themes/magento2-default-theme/**/*.phtml',
            '../../../../../../code/**/*.phtml',
            '../../**/*.phtml',
            '../../../**/*.phtml',
        ],
        options: {
            safelist: [
                // ... a lot of safelist classes
            ],
        },
    }
```

I don't use any regexes in the purge config.

Full error:
```
TypeError: Cannot read property 'filter' of undefined
    at web/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:39:60
    at Array.map (<anonymous>)
    at Root.map (web/tailwind/node_modules/postcss-selector-parser/dist/selectors/container.js:347:23)
    at Processor.func (web/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:38:20)
    at Processor._runSync (web/tailwind/node_modules/postcss-selector-parser/dist/processor.js:102:26)
    at Processor.transformSync (web/tailwind/node_modules/postcss-selector-parser/dist/processor.js:171:17)
    at extractElementSelector (web/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:47:47)
    at web/tailwind/node_modules/tailwindcss/lib/jit/lib/resolveDefaultsAtRules.js:82:30
    at web/tailwind/node_modules/tailwindcss/lib/jit/processTailwindFeatures.js:64:50
    at Object.Once (web/tailwind/node_modules/tailwindcss/lib/cli.js:680:15)
```

Using tailwind 2.2.15, postcss 8.3.1. Happening with `tailwindcss --postcss -i tailwind-source.css -o ../css/styles.css`
